language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-26
    - ANDROID_ABI=x86
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.3
    - android-26

    - extra-google-m2repository
    - extra-android-m2repository

    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
install:
    - echo yes | $ANDROID_HOME/tools/bin/sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
    - echo yes | $ANDROID_HOME/tools/bin/sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
before_script:
    - wget http://services.gradle.org/distributions/gradle-3.3-all.zip
    - unzip -qq gradle-3.3-all.zip
    - export GRADLE_HOME=$PWD/gradle-3.3
    - export PATH=$GRADLE_HOME/bin:$PATH