language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-26
    - ANDROID_ABI=x86
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.3
    - android-26

    - extra-google-m2repository
    - extra-android-m2repository

    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}